CREATE DATABASE CRUD;
USE CRUD;
CREATE TABLE USUARIOS(
  NOME VARCHAR (20) not null,
  EMAIL VARCHAR (20) not null,
  LOGIN VARCHAR (20) not null,
  SENHA VARCHAR (20) not null,
  primary key(EMAIL)
);
CREATE TABLE PRODUTOS(
  PRODUTO VARCHAR (20) not null,
  VALIDADE VARCHAR (20) not null,
  FABRICANTE VARCHAR (20) not null,
  primary key(PRODUTO)
);
CREATE TABLE FORNECEDORES(
  FORNECEDORES VARCHAR (20) not null,
  ENDERECO VARCHAR (20) not null,
  RAZAO_SOCIAL VARCHAR (20) not null,
  CNPJ VARCHAR (20) not null,
  TELEFONE VARCHAR (20) not null,
  primary key (CNPJ)
);
